### ISSUE TITLE
Alpha Release Milestone

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#171]
## What

The first public release of the impact framework. The project is incubation and the release is alpha so there is plenty of signals that the framework can change significantly from this point.

## Why

We're looking for some early adopters to start trying the framework with different use cases and providing feedback so we can learn and improve for subsequent versions.
The repo can change significantly post alpha esp. in response to feedback but it must have _some_ stability so effort is not wasted.
- The CLI is likely to change significantly post feedback.
- The model interface at this point is likely to remain more stable.

### As a user I can write my own **impact manifest files (impls)** using pre-existing models and compute using the CLI.
- [ ] Specification represents the state of the  alpha version.
- [ ] Documentation contains an IMPL writing guide
- [ ] Every model (except built-in) has been moved to another repo
- [ ] All models have great documentation making it easy to use
- [ ] CLI provides useful error messages
- [ ] CLI provides useful debug functionality
- [ ] CLI ensures all components are time-synced before aggregation.
- [ ] CLI support aggregation of impacts.
- [ ] CLI supports output to CSV
- [ ] CLI there is a way to visualize output using graphana
- [ ] CLI prints a clear disclaimer on every use reminding the user this project is experimental and in incubation.
- [ ] CLI prints a clear disclaimer for every unofficial model we created (e.g. we created the wattime model, not watttime) 
- [ ] CLI models have a fallback mode, if an impact is already present skip (e.g. if energy is present, someone has already calculated it and you can skip)

### As a user I can write my **own models** and use them in computing manifest files using the CLI.
- [ ] Documentation contains a model writing guide
- [ ] Documentation contains a model publishing guide
- [ ] units.yml has been updated to ensure all existing params are included
- [ ] CLI can load models dynamically.
- [ ] CLI models are single load, multiple use.

### As a user I can provide feedback to the IEF team about their product.
- [ ] There is an issue template in the IEF repo for providing feedback.
- [ ] There is a discussion forum to ask questions
- [ ] CLI when a severe error is returned, print a link in the console to provide feedback

**Comment by jawache** [comment]
Idea from @narekhovhannisyan - To help our users generate impl files, introduce script to kickstarts an IMPL file (generators).

**Comment by paz** [comment]
> Idea from @narekhovhannisyan - To help our users generate impl files, introduce script to kickstarts an IMPL file (generators). Idea from @paz - building on the idea, an UI/GUI.

hi, cool project, unfortunately i think you have mentioned the wrong paz..

**Comment by jawache** [comment]
> > Idea from @narekhovhannisyan - To help our users generate impl files, introduce script to kickstarts an IMPL file (generators). Idea from @paz - building on the idea, an UI/GUI.
> 
> hi, cool project, unfortunately i think you have mentioned the wrong paz..

Hah oops!
