### ISSUE TITLE
IMP POC for Boavizta

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/ief#49]
**What**: Create an initial PoC for an IMP which interfaces with the Boavizta API.
**Why**: So we can validate the specification and learn from implementation.
**SoW**:
- Create a concrete class that implements our IMI interface to the Boavizta API
- It should have some unit tests that call the class with sample data and prints out the response (note in future we will validate code like that by using the impconsole)

@gnanakeethan as discussed let's approach this task like this:

- [ ] #55 (@jawache to gather)
- [x] Create a `BoaviztaIMP `class which implements the class interface as defined in https://github.com/Green-Software-Foundation/carbon-ql/blob/dev/specs/impact-model-plugin.md
**NOTE**: As discussed let's not strongly type the inputs, keep them as dictionaries/objects. I know the spec has type names but let's assume this as just alias's for object. I'd like us to delay strongly typing things for as long as possible (until we have to). Communicate if the params are wrong type/shape using exceptions.
- [x] Create some code which implements `BoaviztaIMP`  and inputs telemetry etc... and prints output.
- [x] Use JSII as per #43 to create the same code in multiple languages and check the actual generated cod  in as well under different folders.
- [x] Create a pull request with all the files and submit that for review the next meeting. 
**NOTE** the pull request should let us view, compare and comment on the source TS code and the generated code. We'll discuss next call and encourage others to add their comments to the PR.

**Comment by jawache** [comment]
@gnanakeethan as discussed let's approach this task like this:

- [ ] Gather real telemetry examples from the SCI case studies
- [ ] Create a `BoaviztaIMP `class which implements the class interface as defined in https://github.com/Green-Software-Foundation/carbon-ql/blob/dev/specs/impact-model-plugin.md
**NOTE**: As discussed let's not strongly type the inputs, keep them as dictionaries/objects. I know the spec has type names but let's assume this as just alias's for object. I'd like us to delay strongly typing things for as long as possible (until we have to). Communicate if the params are wrong type/shape using exceptions.
- [ ] Create some code which implements `BoaviztaIMP`  and inputs telemetry etc... and prints output.
- [ ] Use JSII as per #43 to create the same code in multiple languages and check the actual generated cod  in as well under different folders.
- [ ] Create a pull request with all the files and submit that for review the next meeting. 
**NOTE** the pull request should let us view, compare and comment on the source TS code and the generated code. We'll discuss next call and encourage others to add their comments to the PR.

**Comment by jawache** [comment]
@gnanakeethan next step in this issue is to focus on these issues

- [ ] Document in detail the limitations you've seen so far in the use of JSII in this ticket https://github.com/Green-Software-Foundation/carbon-ql/issues/43


- [ ] There are some questions about how Promises in JS are handled in other languages, JSII clearly say they support Promises returned from TS.

 Add promises to the Boavizta use case and generate Java and .Net which others will review and check on the next call to see how Promises are reflected in other languages.
- [ ] Add a real test case to the Boavista example, we need to see real-data being passed to snapshot and formatted in a way that works for the Boavista API. We need to pass in telemetry, use the format we have in the IMPL files for now (telemetry in this case is a time series of CPU utilization %ages, so imagine you are using this to measure the energy of a process and all you have is the CPU utilization measured every 5 seconds for a minute)
- [ ] 
 The response needs to be parsed and converted to a normalized response, you can share the response you get from Boavista with me and I can guide you on what the extract and return in the Impact object.
- [ ] For the next CarbonQL call there should be a complete set of test cases for the Boavizta example, all the functions apart from Stream. Telemetry can come in many different shapes and sizes, we'll work to expand the set of telemetry test cases during the week.

**Comment by jawache** [comment]
Superseded by https://github.com/Green-Software-Foundation/ief/issues/66
